(function () {
  window.COUNTRY_CAPITALS = [
    { id: "afg", country: "Afghanistan", capital: "Kabul", continent: "Asia" },
    { id: "alb", country: "Albania", capital: "Tirana", continent: "Europe" },
    { id: "dza", country: "Algeria", capital: "Algiers", continent: "Africa" },
    { id: "and", country: "Andorra", capital: "Andorra la Vella", continent: "Europe" },
    { id: "ago", country: "Angola", capital: "Luanda", continent: "Africa" },
    {
      id: "atg",
      country: "Antigua and Barbuda",
      capital: "Saint John's",
      continent: "North America",
      capitalAliases: ["St John's", "St. John's"],
    },
    { id: "arg", country: "Argentina", capital: "Buenos Aires", continent: "South America" },
    { id: "arm", country: "Armenia", capital: "Yerevan", continent: "Asia" },
    { id: "aus", country: "Australia", capital: "Canberra", continent: "Oceania" },
    { id: "aut", country: "Austria", capital: "Vienna", continent: "Europe" },
    { id: "aze", country: "Azerbaijan", capital: "Baku", continent: "Asia" },
    { id: "bhs", country: "Bahamas", capital: "Nassau", continent: "North America", countryAliases: ["The Bahamas"] },
    { id: "bhr", country: "Bahrain", capital: "Manama", continent: "Asia" },
    { id: "bgd", country: "Bangladesh", capital: "Dhaka", continent: "Asia", capitalAliases: ["Dacca"] },
    { id: "brb", country: "Barbados", capital: "Bridgetown", continent: "North America" },
    { id: "blr", country: "Belarus", capital: "Minsk", continent: "Europe" },
    { id: "bel", country: "Belgium", capital: "Brussels", continent: "Europe" },
    { id: "blz", country: "Belize", capital: "Belmopan", continent: "North America" },
    { id: "ben", country: "Benin", capital: "Porto-Novo", continent: "Africa", capitalAliases: ["Porto Novo", "Cotonou"] },
    { id: "btn", country: "Bhutan", capital: "Thimphu", continent: "Asia" },
    { id: "bol", country: "Bolivia", capital: "Sucre", continent: "South America", capitalAliases: ["La Paz"] },
    {
      id: "bih",
      country: "Bosnia and Herzegovina",
      capital: "Sarajevo",
      continent: "Europe",
      countryAliases: ["Bosnia"],
    },
    { id: "bwa", country: "Botswana", capital: "Gaborone", continent: "Africa" },
    { id: "bra", country: "Brazil", capital: "Brasilia", continent: "South America" },
    { id: "brn", country: "Brunei", capital: "Bandar Seri Begawan", continent: "Asia" },
    { id: "bgr", country: "Bulgaria", capital: "Sofia", continent: "Europe" },
    { id: "bfa", country: "Burkina Faso", capital: "Ouagadougou", continent: "Africa" },
    { id: "bdi", country: "Burundi", capital: "Gitega", continent: "Africa", capitalAliases: ["Bujumbura"] },
    { id: "cpv", country: "Cabo Verde", capital: "Praia", continent: "Africa", countryAliases: ["Cape Verde"] },
    { id: "khm", country: "Cambodia", capital: "Phnom Penh", continent: "Asia" },
    { id: "cmr", country: "Cameroon", capital: "Yaounde", continent: "Africa" },
    { id: "can", country: "Canada", capital: "Ottawa", continent: "North America" },
    { id: "caf", country: "Central African Republic", capital: "Bangui", continent: "Africa" },
    { id: "tcd", country: "Chad", capital: "N'Djamena", continent: "Africa", capitalAliases: ["Ndjamena"] },
    { id: "chl", country: "Chile", capital: "Santiago", continent: "South America" },
    { id: "chn", country: "China", capital: "Beijing", continent: "Asia" },
    { id: "col", country: "Colombia", capital: "Bogota", continent: "South America" },
    { id: "com", country: "Comoros", capital: "Moroni", continent: "Africa" },
    {
      id: "cog",
      country: "Republic of the Congo",
      capital: "Brazzaville",
      continent: "Africa",
      countryAliases: ["Congo", "Congo-Brazzaville", "Congo Brazzaville"],
    },
    { id: "cri", country: "Costa Rica", capital: "San Jose", continent: "North America" },
    {
      id: "civ",
      country: "Cote d'Ivoire",
      capital: "Yamoussoukro",
      continent: "Africa",
      countryAliases: ["Ivory Coast"],
    },
    { id: "hrv", country: "Croatia", capital: "Zagreb", continent: "Europe" },
    { id: "cub", country: "Cuba", capital: "Havana", continent: "North America" },
    { id: "cyp", country: "Cyprus", capital: "Nicosia", continent: "Asia" },
    { id: "cze", country: "Czechia", capital: "Prague", continent: "Europe", countryAliases: ["Czech Republic"] },
    {
      id: "cod",
      country: "Democratic Republic of the Congo",
      capital: "Kinshasa",
      continent: "Africa",
      countryAliases: ["DR Congo", "DRC", "Congo-Kinshasa", "Congo Kinshasa"],
    },
    { id: "dnk", country: "Denmark", capital: "Copenhagen", continent: "Europe" },
    { id: "dji", country: "Djibouti", capital: "Djibouti", continent: "Africa" },
    { id: "dma", country: "Dominica", capital: "Roseau", continent: "North America" },
    { id: "dom", country: "Dominican Republic", capital: "Santo Domingo", continent: "North America" },
    { id: "ecu", country: "Ecuador", capital: "Quito", continent: "South America" },
    { id: "egy", country: "Egypt", capital: "Cairo", continent: "Africa" },
    { id: "slv", country: "El Salvador", capital: "San Salvador", continent: "North America" },
    { id: "gnq", country: "Equatorial Guinea", capital: "Malabo", continent: "Africa" },
    { id: "eri", country: "Eritrea", capital: "Asmara", continent: "Africa" },
    { id: "est", country: "Estonia", capital: "Tallinn", continent: "Europe" },
    { id: "swz", country: "Eswatini", capital: "Mbabane", continent: "Africa", countryAliases: ["Swaziland"], capitalAliases: ["Lobamba"] },
    { id: "eth", country: "Ethiopia", capital: "Addis Ababa", continent: "Africa" },
    { id: "fji", country: "Fiji", capital: "Suva", continent: "Oceania" },
    { id: "fin", country: "Finland", capital: "Helsinki", continent: "Europe" },
    { id: "fra", country: "France", capital: "Paris", continent: "Europe" },
    { id: "gab", country: "Gabon", capital: "Libreville", continent: "Africa" },
    { id: "gmb", country: "The Gambia", capital: "Banjul", continent: "Africa", countryAliases: ["Gambia"] },
    { id: "geo", country: "Georgia", capital: "Tbilisi", continent: "Asia" },
    { id: "deu", country: "Germany", capital: "Berlin", continent: "Europe" },
    { id: "gha", country: "Ghana", capital: "Accra", continent: "Africa" },
    { id: "grc", country: "Greece", capital: "Athens", continent: "Europe" },
    { id: "grd", country: "Grenada", capital: "Saint George's", continent: "North America", capitalAliases: ["St George's", "St. George's"] },
    { id: "gtm", country: "Guatemala", capital: "Guatemala City", continent: "North America" },
    { id: "gin", country: "Guinea", capital: "Conakry", continent: "Africa" },
    { id: "gnb", country: "Guinea-Bissau", capital: "Bissau", continent: "Africa", countryAliases: ["Guinea Bissau"] },
    { id: "guy", country: "Guyana", capital: "Georgetown", continent: "South America" },
    { id: "hti", country: "Haiti", capital: "Port-au-Prince", continent: "North America", capitalAliases: ["Port au Prince"] },
    { id: "hnd", country: "Honduras", capital: "Tegucigalpa", continent: "North America" },
    { id: "hun", country: "Hungary", capital: "Budapest", continent: "Europe" },
    { id: "isl", country: "Iceland", capital: "Reykjavik", continent: "Europe" },
    { id: "ind", country: "India", capital: "New Delhi", continent: "Asia" },
    { id: "idn", country: "Indonesia", capital: "Jakarta", continent: "Asia" },
    { id: "irn", country: "Iran", capital: "Tehran", continent: "Asia" },
    { id: "irq", country: "Iraq", capital: "Baghdad", continent: "Asia" },
    { id: "irl", country: "Ireland", capital: "Dublin", continent: "Europe" },
    { id: "isr", country: "Israel", capital: "Jerusalem", continent: "Asia" },
    { id: "ita", country: "Italy", capital: "Rome", continent: "Europe" },
    { id: "jam", country: "Jamaica", capital: "Kingston", continent: "North America" },
    { id: "jpn", country: "Japan", capital: "Tokyo", continent: "Asia" },
    { id: "jor", country: "Jordan", capital: "Amman", continent: "Asia" },
    { id: "kaz", country: "Kazakhstan", capital: "Astana", continent: "Asia", capitalAliases: ["Nur-Sultan", "Nur Sultan"] },
    { id: "ken", country: "Kenya", capital: "Nairobi", continent: "Africa" },
    { id: "kir", country: "Kiribati", capital: "South Tarawa", continent: "Oceania", capitalAliases: ["Tarawa"] },
    { id: "kwt", country: "Kuwait", capital: "Kuwait City", continent: "Asia" },
    { id: "kgz", country: "Kyrgyzstan", capital: "Bishkek", continent: "Asia" },
    { id: "lao", country: "Laos", capital: "Vientiane", continent: "Asia", countryAliases: ["Lao PDR"] },
    { id: "lva", country: "Latvia", capital: "Riga", continent: "Europe" },
    { id: "lbn", country: "Lebanon", capital: "Beirut", continent: "Asia" },
    { id: "lso", country: "Lesotho", capital: "Maseru", continent: "Africa" },
    { id: "lbr", country: "Liberia", capital: "Monrovia", continent: "Africa" },
    { id: "lby", country: "Libya", capital: "Tripoli", continent: "Africa" },
    { id: "lie", country: "Liechtenstein", capital: "Vaduz", continent: "Europe" },
    { id: "ltu", country: "Lithuania", capital: "Vilnius", continent: "Europe" },
    { id: "lux", country: "Luxembourg", capital: "Luxembourg", continent: "Europe", capitalAliases: ["Luxembourg City"] },
    { id: "mdg", country: "Madagascar", capital: "Antananarivo", continent: "Africa" },
    { id: "mwi", country: "Malawi", capital: "Lilongwe", continent: "Africa" },
    { id: "mys", country: "Malaysia", capital: "Kuala Lumpur", continent: "Asia" },
    { id: "mdv", country: "Maldives", capital: "Male", continent: "Asia" },
    { id: "mli", country: "Mali", capital: "Bamako", continent: "Africa" },
    { id: "mlt", country: "Malta", capital: "Valletta", continent: "Europe" },
    { id: "mhl", country: "Marshall Islands", capital: "Majuro", continent: "Oceania" },
    { id: "mrt", country: "Mauritania", capital: "Nouakchott", continent: "Africa" },
    { id: "mus", country: "Mauritius", capital: "Port Louis", continent: "Africa" },
    { id: "mex", country: "Mexico", capital: "Mexico City", continent: "North America" },
    {
      id: "fsm",
      country: "Federated States of Micronesia",
      capital: "Palikir",
      continent: "Oceania",
      countryAliases: ["Micronesia"],
    },
    { id: "mda", country: "Moldova", capital: "Chisinau", continent: "Europe" },
    { id: "mco", country: "Monaco", capital: "Monaco", continent: "Europe", capitalAliases: ["Monaco City"] },
    { id: "mng", country: "Mongolia", capital: "Ulaanbaatar", continent: "Asia", capitalAliases: ["Ulan Bator"] },
    { id: "mne", country: "Montenegro", capital: "Podgorica", continent: "Europe" },
    { id: "mar", country: "Morocco", capital: "Rabat", continent: "Africa" },
    { id: "moz", country: "Mozambique", capital: "Maputo", continent: "Africa" },
    { id: "mmr", country: "Myanmar", capital: "Naypyidaw", continent: "Asia", countryAliases: ["Burma"], capitalAliases: ["Nay Pyi Taw"] },
    { id: "nam", country: "Namibia", capital: "Windhoek", continent: "Africa" },
    { id: "nru", country: "Nauru", capital: "Yaren", continent: "Oceania", capitalAliases: ["Yaren District"] },
    { id: "npl", country: "Nepal", capital: "Kathmandu", continent: "Asia" },
    { id: "nld", country: "Netherlands", capital: "Amsterdam", continent: "Europe", capitalAliases: ["The Hague"] },
    { id: "nzl", country: "New Zealand", capital: "Wellington", continent: "Oceania" },
    { id: "nic", country: "Nicaragua", capital: "Managua", continent: "North America" },
    { id: "ner", country: "Niger", capital: "Niamey", continent: "Africa" },
    { id: "nga", country: "Nigeria", capital: "Abuja", continent: "Africa" },
    { id: "prk", country: "North Korea", capital: "Pyongyang", continent: "Asia", countryAliases: ["DPRK"] },
    { id: "mkd", country: "North Macedonia", capital: "Skopje", continent: "Europe", countryAliases: ["Macedonia"] },
    { id: "nor", country: "Norway", capital: "Oslo", continent: "Europe" },
    { id: "omn", country: "Oman", capital: "Muscat", continent: "Asia" },
    { id: "pak", country: "Pakistan", capital: "Islamabad", continent: "Asia" },
    { id: "plw", country: "Palau", capital: "Ngerulmud", continent: "Oceania" },
    { id: "pan", country: "Panama", capital: "Panama City", continent: "North America" },
    { id: "png", country: "Papua New Guinea", capital: "Port Moresby", continent: "Oceania" },
    { id: "pry", country: "Paraguay", capital: "Asuncion", continent: "South America" },
    { id: "per", country: "Peru", capital: "Lima", continent: "South America" },
    { id: "phl", country: "Philippines", capital: "Manila", continent: "Asia" },
    { id: "pol", country: "Poland", capital: "Warsaw", continent: "Europe" },
    { id: "prt", country: "Portugal", capital: "Lisbon", continent: "Europe" },
    { id: "qat", country: "Qatar", capital: "Doha", continent: "Asia" },
    { id: "rou", country: "Romania", capital: "Bucharest", continent: "Europe" },
    { id: "rus", country: "Russia", capital: "Moscow", continent: "Europe", countryAliases: ["Russian Federation"] },
    { id: "rwa", country: "Rwanda", capital: "Kigali", continent: "Africa" },
    { id: "kna", country: "Saint Kitts and Nevis", capital: "Basseterre", continent: "North America", countryAliases: ["St Kitts and Nevis"] },
    { id: "lca", country: "Saint Lucia", capital: "Castries", continent: "North America", countryAliases: ["St Lucia"] },
    {
      id: "vct",
      country: "Saint Vincent and the Grenadines",
      capital: "Kingstown",
      continent: "North America",
      countryAliases: ["St Vincent and the Grenadines"],
    },
    { id: "wsm", country: "Samoa", capital: "Apia", continent: "Oceania" },
    { id: "smr", country: "San Marino", capital: "San Marino", continent: "Europe" },
    { id: "stp", country: "Sao Tome and Principe", capital: "Sao Tome", continent: "Africa" },
    { id: "sau", country: "Saudi Arabia", capital: "Riyadh", continent: "Asia" },
    { id: "sen", country: "Senegal", capital: "Dakar", continent: "Africa" },
    { id: "srb", country: "Serbia", capital: "Belgrade", continent: "Europe" },
    { id: "syc", country: "Seychelles", capital: "Victoria", continent: "Africa" },
    { id: "sle", country: "Sierra Leone", capital: "Freetown", continent: "Africa" },
    { id: "sgp", country: "Singapore", capital: "Singapore", continent: "Asia", capitalAliases: ["Singapore City"] },
    { id: "svk", country: "Slovakia", capital: "Bratislava", continent: "Europe" },
    { id: "svn", country: "Slovenia", capital: "Ljubljana", continent: "Europe" },
    { id: "slb", country: "Solomon Islands", capital: "Honiara", continent: "Oceania" },
    { id: "som", country: "Somalia", capital: "Mogadishu", continent: "Africa" },
    {
      id: "zaf",
      country: "South Africa",
      capital: "Pretoria",
      continent: "Africa",
      capitalAliases: ["Cape Town", "Bloemfontein"],
    },
    { id: "kor", country: "South Korea", capital: "Seoul", continent: "Asia", countryAliases: ["Republic of Korea"] },
    { id: "ssd", country: "South Sudan", capital: "Juba", continent: "Africa" },
    { id: "esp", country: "Spain", capital: "Madrid", continent: "Europe" },
    { id: "lka", country: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", continent: "Asia", capitalAliases: ["Colombo", "Kotte"] },
    { id: "sdn", country: "Sudan", capital: "Khartoum", continent: "Africa" },
    { id: "sur", country: "Suriname", capital: "Paramaribo", continent: "South America" },
    { id: "swe", country: "Sweden", capital: "Stockholm", continent: "Europe" },
    { id: "che", country: "Switzerland", capital: "Bern", continent: "Europe", capitalAliases: ["Berne"] },
    { id: "syr", country: "Syria", capital: "Damascus", continent: "Asia" },
    { id: "tjk", country: "Tajikistan", capital: "Dushanbe", continent: "Asia" },
    { id: "tza", country: "Tanzania", capital: "Dodoma", continent: "Africa", capitalAliases: ["Dar es Salaam"] },
    { id: "tha", country: "Thailand", capital: "Bangkok", continent: "Asia" },
    { id: "tls", country: "Timor-Leste", capital: "Dili", continent: "Asia", countryAliases: ["East Timor", "Timor Leste"] },
    { id: "tgo", country: "Togo", capital: "Lome", continent: "Africa" },
    { id: "ton", country: "Tonga", capital: "Nuku'alofa", continent: "Oceania", capitalAliases: ["Nukualofa"] },
    { id: "tto", country: "Trinidad and Tobago", capital: "Port of Spain", continent: "North America" },
    { id: "tun", country: "Tunisia", capital: "Tunis", continent: "Africa" },
    { id: "tur", country: "Turkey", capital: "Ankara", continent: "Asia", countryAliases: ["Turkiye"] },
    { id: "tkm", country: "Turkmenistan", capital: "Ashgabat", continent: "Asia" },
    { id: "tuv", country: "Tuvalu", capital: "Funafuti", continent: "Oceania" },
    { id: "uga", country: "Uganda", capital: "Kampala", continent: "Africa" },
    { id: "ukr", country: "Ukraine", capital: "Kyiv", continent: "Europe", capitalAliases: ["Kiev"] },
    { id: "are", country: "United Arab Emirates", capital: "Abu Dhabi", continent: "Asia", countryAliases: ["UAE"] },
    {
      id: "gbr",
      country: "United Kingdom",
      capital: "London",
      continent: "Europe",
      countryAliases: ["UK", "Great Britain", "Britain"],
    },
    {
      id: "usa",
      country: "United States",
      capital: "Washington, D.C.",
      continent: "North America",
      countryAliases: ["United States of America", "USA", "US", "America"],
      capitalAliases: ["Washington DC", "Washington"],
    },
    { id: "ury", country: "Uruguay", capital: "Montevideo", continent: "South America" },
    { id: "uzb", country: "Uzbekistan", capital: "Tashkent", continent: "Asia" },
    { id: "vut", country: "Vanuatu", capital: "Port Vila", continent: "Oceania" },
    { id: "ven", country: "Venezuela", capital: "Caracas", continent: "South America" },
    { id: "vnm", country: "Vietnam", capital: "Hanoi", continent: "Asia" },
    { id: "yem", country: "Yemen", capital: "Sanaa", continent: "Asia", capitalAliases: ["Sana'a"] },
    { id: "zmb", country: "Zambia", capital: "Lusaka", continent: "Africa" },
    { id: "zwe", country: "Zimbabwe", capital: "Harare", continent: "Africa" },
  ];
})();
