(function () {
  var facts = {
    afg: "Kabul sits high in a mountain valley, making Afghanistan's capital one of Asia's higher capital cities.",
    alb: "Tirana, Albania's capital, is known for Skanderbeg Square and a center brightened with colorful buildings.",
    dza: "Algiers, Algeria's capital, is nicknamed Algiers the White because of its pale buildings above the Mediterranean.",
    and: "Andorra la Vella, Andorra's capital, is one of Europe's highest capitals at more than 1,000 meters above sea level.",
    ago: "Luanda, Angola's capital, grew around a natural Atlantic harbor that helped make it a major port city.",
    atg: "Saint John's, the capital of Antigua and Barbuda, is famous for its twin-towered cathedral above the harbor.",
    arg: "Buenos Aires, Argentina's capital, is closely tied to tango, a dance and music style born around the River Plate.",
    arm: "Yerevan, Armenia's capital, is often called the Pink City because many buildings use rose-colored volcanic tuff.",
    aus: "Canberra, Australia's capital, was purpose-built after Sydney and Melbourne both wanted the national capital role.",
    aut: "Vienna, Austria's capital, has long been called the City of Music thanks to composers such as Mozart and Beethoven.",
    aze: "Baku, Azerbaijan's capital, sits beside the Caspian Sea and is one of the world's lowest-lying capitals.",
    bhs: "Nassau, the capital of The Bahamas, is on New Providence island and grew from a busy colonial harbor.",
    bhr: "Manama, Bahrain's capital, is a Gulf trading city whose name is often linked with the idea of a resting place.",
    bgd: "Dhaka, Bangladesh's capital, is famous for its huge number of cycle rickshaws and its lively old city streets.",
    brb: "Bridgetown, the capital of Barbados, has a historic garrison area recognized by UNESCO.",
    blr: "Minsk, Belarus's capital, was heavily rebuilt after World War II, which is why many of its avenues feel broad and planned.",
    bel: "Brussels, Belgium's capital, is also a major European Union hub, so it is often called the capital of Europe.",
    blz: "Belmopan became Belize's capital after Hurricane Hattie badly damaged the old capital, Belize City, in 1961.",
    ben: "Porto-Novo is Benin's official capital, while nearby Cotonou handles much of the country's government business.",
    btn: "Thimphu, Bhutan's capital, is famous for using a traffic officer at its main junction instead of traffic lights.",
    bol: "Sucre is Bolivia's constitutional capital, while La Paz hosts the seat of government high in the Andes.",
    bih: "Sarajevo, Bosnia and Herzegovina's capital, is known for having mosques, churches, and synagogues close together.",
    bwa: "Gaborone, Botswana's capital, grew rapidly after independence from a small settlement near the South African border.",
    bra: "Brasilia, Brazil's capital, is a planned city whose central layout is often compared to an airplane or bird.",
    brn: "Bandar Seri Begawan, Brunei's capital, is known for the golden dome of the Omar Ali Saifuddien Mosque.",
    bgr: "Sofia, Bulgaria's capital, sits close to Vitosha Mountain, so the skyline often has a mountain backdrop.",
    bfa: "Ouagadougou, Burkina Faso's capital, is so often shortened that many people simply call it Ouaga.",
    bdi: "Gitega became Burundi's political capital in 2019, restoring a role it held during the country's royal era.",
    cpv: "Praia, the capital of Cabo Verde, means beach in Portuguese and sits on Santiago island.",
    khm: "Phnom Penh, Cambodia's capital, stands where the Mekong, Tonle Sap, and Bassac rivers meet.",
    cmr: "Yaounde, Cameroon's capital, is built across rolling hills in the country's forested south-central region.",
    can: "Ottawa became Canada's capital after Queen Victoria chose it, partly because it sat between English and French Canada.",
    caf: "Bangui, the capital of the Central African Republic, sits on the Ubangi River opposite the Democratic Republic of the Congo.",
    tcd: "N'Djamena, Chad's capital, stands near the meeting of the Chari and Logone rivers.",
    chl: "Santiago, Chile's capital, sits in a broad valley with the Andes rising dramatically to the east.",
    chn: "Beijing, China's capital, means Northern Capital and is home to the Forbidden City.",
    col: "Bogota, Colombia's capital, is one of the world's highest large capital cities, sitting on an Andean plateau.",
    com: "Moroni, the capital of Comoros, sits on Grande Comore island near the active volcano Mount Karthala.",
    cog: "Brazzaville, the capital of the Republic of the Congo, faces Kinshasa across the Congo River.",
    cri: "San Jose, Costa Rica's capital, sits in the country's Central Valley between volcanic mountain ranges.",
    civ: "Yamoussoukro, Cote d'Ivoire's capital, is known for its enormous Basilica of Our Lady of Peace.",
    hrv: "Zagreb, Croatia's capital, has an old upper town and a newer lower town linked by a very short funicular.",
    cub: "Havana, Cuba's capital, has a colorful old town and a harbor that made it one of the Caribbean's great port cities.",
    cyp: "Nicosia, Cyprus's capital, is often described as the last divided capital in Europe.",
    cze: "Prague, Czechia's capital, is famous for its medieval Astronomical Clock in the Old Town Square.",
    cod: "Kinshasa, capital of the Democratic Republic of the Congo, faces Brazzaville across the Congo River.",
    dnk: "Copenhagen, Denmark's capital, is known for cycling culture and a harbor clean enough for swimming areas.",
    dji: "Djibouti, the capital of Djibouti, sits by the Gulf of Tadjoura near one of the world's busiest shipping routes.",
    dma: "Roseau, Dominica's capital, is a compact Caribbean city tucked between the sea and steep green hills.",
    dom: "Santo Domingo, the Dominican Republic's capital, has one of the oldest European-built city centers in the Americas.",
    ecu: "Quito, Ecuador's capital, sits high in the Andes and lies close to the equator.",
    egy: "Cairo, Egypt's capital, stands beside the Nile and is only a short journey from the pyramids of Giza.",
    slv: "San Salvador, El Salvador's capital, sits in a valley watched over by the San Salvador volcano.",
    gnq: "Malabo, Equatorial Guinea's capital, is on Bioko island rather than on the country's mainland.",
    eri: "Asmara, Eritrea's capital, is famous for its preserved modernist and Art Deco architecture.",
    est: "Tallinn, Estonia's capital, has a walled medieval old town that looks almost storybook from above.",
    swz: "Mbabane is Eswatini's administrative capital, while Lobamba is the royal and legislative capital.",
    eth: "Addis Ababa, Ethiopia's capital, hosts the headquarters of the African Union.",
    fji: "Suva, Fiji's capital, is one of the South Pacific's largest urban centers and a regional university hub.",
    fin: "Helsinki, Finland's capital, spreads across a peninsula and many nearby islands on the Gulf of Finland.",
    fra: "Paris, France's capital, grew along the River Seine and is one of the world's most visited cities.",
    gab: "Libreville, Gabon's capital, means free town and was founded near the Atlantic coast.",
    gmb: "Banjul, The Gambia's capital, sits on an island at the mouth of the Gambia River.",
    geo: "Tbilisi, Georgia's capital, takes its name from warm springs found in the area.",
    deu: "Berlin, Germany's capital, has a UNESCO-listed Museum Island in the River Spree.",
    gha: "Accra, Ghana's capital, sits on the Gulf of Guinea and blends beaches, markets, and historic forts.",
    grc: "Athens, Greece's capital, is overlooked by the Acropolis, one of the most famous ancient sites in the world.",
    grd: "Saint George's, Grenada's capital, curves around a horseshoe-shaped harbor.",
    gtm: "Guatemala City, Guatemala's capital, sits in a highland valley surrounded by volcanoes.",
    gin: "Conakry, Guinea's capital, grew from an island settlement into a city spreading onto the Kaloum Peninsula.",
    gnb: "Bissau, Guinea-Bissau's capital, sits beside the Geba River estuary near the Atlantic Ocean.",
    guy: "Georgetown, Guyana's capital, lies below sea level in places and is protected by sea walls and canals.",
    hti: "Port-au-Prince, Haiti's capital, sits on a bay of the Gulf of Gonave.",
    hnd: "Tegucigalpa, Honduras's capital, is set in mountain terrain and is often nicknamed Tegus.",
    hun: "Budapest, Hungary's capital, was formed in 1873 by joining Buda, Pest, and Obuda.",
    isl: "Reykjavik, Iceland's capital, is the world's northernmost capital of a sovereign state.",
    ind: "New Delhi, India's capital, was planned in the early 20th century with broad avenues and ceremonial spaces.",
    idn: "Jakarta remains Indonesia's functioning capital while Nusantara is being built as a future political capital.",
    irn: "Tehran, Iran's capital, sits at the foot of the Alborz Mountains.",
    irq: "Baghdad, Iraq's capital, was once a major center of learning during the Islamic Golden Age.",
    irl: "Dublin, Ireland's capital, grew around the River Liffey and a Viking settlement.",
    isr: "Jerusalem, Israel's capital, is one of the world's oldest cities and is sacred to several major religions.",
    ita: "Rome, Italy's capital, contains the Colosseum and surrounds Vatican City.",
    jam: "Kingston, Jamaica's capital, sits beside the world's seventh-largest natural harbor.",
    jpn: "Tokyo, Japan's capital, began as Edo and became the imperial capital in the 19th century.",
    jor: "Amman, Jordan's capital, was built across hills and contains Roman ruins in its city center.",
    kaz: "Astana, Kazakhstan's capital, is known for futuristic architecture on the steppe.",
    ken: "Nairobi, Kenya's capital, has a national park where wildlife lives within sight of city buildings.",
    kir: "South Tarawa, Kiribati's capital area, is a chain of islets on a narrow coral atoll.",
    kwt: "Kuwait City, Kuwait's capital, is known for the Kuwait Towers on the edge of the Persian Gulf.",
    kgz: "Bishkek, Kyrgyzstan's capital, sits near the snow-capped Tian Shan mountains.",
    lao: "Vientiane, Laos's capital, sits beside the Mekong River across from Thailand.",
    lva: "Riga, Latvia's capital, is famous for its Art Nouveau architecture and old Hanseatic trading history.",
    lbn: "Beirut, Lebanon's capital, stands on a Mediterranean peninsula and has been inhabited for thousands of years.",
    lso: "Maseru, Lesotho's capital, sits on the Caledon River right by the border with South Africa.",
    lbr: "Monrovia, Liberia's capital, is named after U.S. President James Monroe.",
    lby: "Tripoli, Libya's capital, has a Mediterranean old city whose name means three cities.",
    lie: "Vaduz, Liechtenstein's capital, is watched over by a castle that is still home to the princely family.",
    ltu: "Vilnius, Lithuania's capital, has a large Baroque old town recognized by UNESCO.",
    lux: "Luxembourg, the capital of Luxembourg, is built across dramatic cliffs and deep river valleys.",
    mdg: "Antananarivo, Madagascar's capital, is often shortened to Tana and sits in the island's central highlands.",
    mwi: "Lilongwe became Malawi's capital in 1975, replacing the older capital of Zomba.",
    mys: "Kuala Lumpur is Malaysia's national capital, while nearby Putrajaya handles many federal administrative offices.",
    mdv: "Male, the Maldives' capital, is one of the world's most densely populated capital cities.",
    mli: "Bamako, Mali's capital, sits on the Niger River and grew as a trading center.",
    mlt: "Valletta, Malta's capital, is one of Europe's smallest capital cities and is packed with historic fortifications.",
    mhl: "Majuro, the Marshall Islands' capital, is an atoll made up of dozens of low coral islets.",
    mrt: "Nouakchott, Mauritania's capital, grew from a small village into a capital city after independence.",
    mus: "Port Louis, Mauritius's capital, has a busy harbor and a historic waterfront at the foot of mountains.",
    mex: "Mexico City, Mexico's capital, was built on the site of the Aztec city of Tenochtitlan.",
    fsm: "Palikir, capital of the Federated States of Micronesia, sits on the island of Pohnpei.",
    mda: "Chisinau, Moldova's capital, is known for leafy parks and boulevards.",
    mco: "Monaco is a city-state, so Monaco is both the country and its capital.",
    mng: "Ulaanbaatar, Mongolia's capital, is often called the coldest national capital in the world.",
    mne: "Podgorica, Montenegro's capital, was called Titograd for much of the 20th century.",
    mar: "Rabat, Morocco's capital, sits where the Bou Regreg River meets the Atlantic Ocean.",
    moz: "Maputo, Mozambique's capital, is known for its Indian Ocean setting and distinctive railway station.",
    mmr: "Naypyidaw, Myanmar's capital, is a purpose-built city that replaced Yangon as capital in 2005.",
    nam: "Windhoek, Namibia's capital, sits in the country's central highlands between desert regions.",
    nru: "Yaren is where Nauru's government offices sit, even though Nauru has no official capital city.",
    npl: "Kathmandu, Nepal's capital, lies in a valley filled with temples, stupas, and old royal squares.",
    nld: "Amsterdam is the Netherlands' capital, while The Hague hosts the government and royal court.",
    nzl: "Wellington, New Zealand's capital, is known for strong winds and a compact harbor setting.",
    nic: "Managua, Nicaragua's capital, sits on the shore of Lake Managua.",
    ner: "Niamey, Niger's capital, stands on the Niger River near the country's southwest corner.",
    nga: "Abuja, Nigeria's capital, was planned to replace Lagos and officially became capital in 1991.",
    prk: "Pyongyang, North Korea's capital, sits on the Taedong River.",
    mkd: "Skopje, North Macedonia's capital, was heavily rebuilt after a major earthquake in 1963.",
    nor: "Oslo, Norway's capital, sits at the head of Oslofjord with forests and islands close to the city center.",
    omn: "Muscat, Oman's capital, is framed by rocky mountains and the Gulf of Oman.",
    pak: "Islamabad, Pakistan's capital, is a planned city built near the Margalla Hills.",
    plw: "Ngerulmud, Palau's capital, became the seat of government in 2006 and is one of the least populated capitals.",
    pan: "Panama City, Panama's capital, stands at the Pacific entrance to the Panama Canal.",
    png: "Port Moresby, Papua New Guinea's capital, sits on a natural harbor on the country's southern coast.",
    pry: "Asuncion, Paraguay's capital, is one of South America's oldest cities founded by Europeans.",
    per: "Lima, Peru's capital, sits on the Pacific coast beside a desert and was once the center of Spanish South America.",
    phl: "Manila, the Philippines' capital, is part of a huge metro area on Manila Bay.",
    pol: "Warsaw, Poland's capital, rebuilt its old town so carefully after World War II that it became a UNESCO site.",
    prt: "Lisbon, Portugal's capital, spreads over hills beside the Tagus River.",
    qat: "Doha, Qatar's capital, grew from a pearling and fishing settlement into a modern Gulf city.",
    rou: "Bucharest, Romania's capital, was once nicknamed Little Paris for its architecture and cafe culture.",
    rus: "Moscow, Russia's capital, is centered on the Kremlin and Red Square.",
    rwa: "Kigali, Rwanda's capital, is known for its hills and famously clean streets.",
    kna: "Basseterre, the capital of Saint Kitts and Nevis, sits on Saint Kitts island by a sheltered bay.",
    lca: "Castries, Saint Lucia's capital, has a deep natural harbor that welcomes cruise ships.",
    vct: "Kingstown, capital of Saint Vincent and the Grenadines, is known for historic churches and a botanical garden.",
    wsm: "Apia, Samoa's capital, sits on Upolu island and was home to writer Robert Louis Stevenson.",
    smr: "San Marino's capital is also called San Marino and sits high on Monte Titano.",
    stp: "Sao Tome, capital of Sao Tome and Principe, sits on the larger island of Sao Tome near the equator.",
    sau: "Riyadh, Saudi Arabia's capital, grew from an oasis settlement into a vast desert metropolis.",
    sen: "Dakar, Senegal's capital, sits on the Cap-Vert peninsula, the westernmost point of mainland Africa.",
    srb: "Belgrade, Serbia's capital, stands where the Danube and Sava rivers meet.",
    syc: "Victoria, Seychelles' capital, is one of the world's smallest capitals and has a famous little clock tower.",
    sle: "Freetown, Sierra Leone's capital, was founded as a settlement for freed formerly enslaved people.",
    sgp: "Singapore is both a country and a city, so Singapore is also the capital name.",
    svk: "Bratislava, Slovakia's capital, lies close to both Austria and Hungary.",
    svn: "Ljubljana, Slovenia's capital, is known for its riverside old town and dragon symbols.",
    slb: "Honiara, the Solomon Islands' capital, sits on Guadalcanal island.",
    som: "Mogadishu, Somalia's capital, is an old Indian Ocean port city.",
    zaf: "Pretoria is South Africa's executive capital, while Cape Town is legislative and Bloemfontein is judicial.",
    kor: "Seoul, South Korea's capital, sits on the Han River and has royal palaces among its skyscrapers.",
    ssd: "Juba, South Sudan's capital, sits on the White Nile.",
    esp: "Madrid, Spain's capital, is one of Europe's highest major capitals.",
    lka: "Sri Jayawardenepura Kotte is Sri Lanka's legislative capital, while nearby Colombo is the commercial hub.",
    sdn: "Khartoum, Sudan's capital, stands where the Blue Nile and White Nile meet.",
    sur: "Paramaribo, Suriname's capital, is known for wooden colonial buildings in its historic center.",
    swe: "Stockholm, Sweden's capital, is spread across islands between Lake Malaren and the Baltic Sea.",
    che: "Bern, Switzerland's capital, has an old town wrapped by a bend in the Aare River.",
    syr: "Damascus, Syria's capital, is often described as one of the world's oldest continuously inhabited cities.",
    tjk: "Dushanbe, Tajikistan's capital, takes its name from a Monday market once held there.",
    tza: "Dodoma is Tanzania's official capital, while Dar es Salaam remains the country's largest city and business hub.",
    tha: "Bangkok, Thailand's capital, has a ceremonial full name that is famously much longer than Bangkok.",
    tls: "Dili, Timor-Leste's capital, sits on the north coast of one of the world's youngest countries.",
    tgo: "Lome, Togo's capital, sits on the Gulf of Guinea close to the border with Ghana.",
    ton: "Nuku'alofa, Tonga's capital, means abode of love in Tongan.",
    tto: "Port of Spain, Trinidad and Tobago's capital, is famous for Carnival celebrations.",
    tun: "Tunis, Tunisia's capital, sits near the ancient ruins of Carthage.",
    tur: "Ankara became Turkey's capital after the republic was founded, replacing imperial Istanbul in that role.",
    tkm: "Ashgabat, Turkmenistan's capital, is known for white marble buildings and grand monuments.",
    tuv: "Funafuti, Tuvalu's capital atoll, is so narrow in places that ocean and lagoon are both nearby.",
    uga: "Kampala, Uganda's capital, was originally built across seven hills.",
    ukr: "Kyiv, Ukraine's capital, stands on the Dnipro River and is one of Eastern Europe's oldest cities.",
    are: "Abu Dhabi, the United Arab Emirates' capital, is also the largest emirate by area.",
    gbr: "London, the United Kingdom's capital, has the world's oldest underground railway system.",
    usa: "Washington, D.C., the United States capital, was planned as a federal district rather than part of a state.",
    ury: "Montevideo, Uruguay's capital, sits on the Rio de la Plata and has a long waterfront promenade.",
    uzb: "Tashkent, Uzbekistan's capital, has long been an important city on Central Asian trade routes.",
    vut: "Port Vila, Vanuatu's capital, sits around a harbor on the island of Efate.",
    ven: "Caracas, Venezuela's capital, lies in a mountain valley near the Caribbean coast.",
    vnm: "Hanoi, Vietnam's capital, is known for its lakes, old quarter, and long history as a political center.",
    yem: "Sanaa, Yemen's capital, is famous for tower houses decorated with white geometric patterns.",
    zmb: "Lusaka, Zambia's capital, sits near the country's center and grew around a railway route.",
    zwe: "Harare, Zimbabwe's capital, was once called Salisbury and is known for flowering jacaranda trees.",
  };

  window.COUNTRY_FUN_FACTS = facts;

  if (window.COUNTRY_CAPITALS) {
    window.COUNTRY_CAPITALS.forEach(function (card) {
      card.fact = facts[card.id] || "";
    });
  }
})();
